import type { MediaItem, PhoneFile, ServiceItem, Song, ThemePreset } from "./types";

export const phoneFiles: PhoneFile[] = [
  { id: "p1", name: "Sunday_Welcome.mov", kind: "video", size: "186 MB", date: "Today 9:12", hue: 28 },
  { id: "p2", name: "Choir_Rehearsal.mov", kind: "video", size: "241 MB", date: "Today 9:18", hue: 200 },
  { id: "p3", name: "Altar_Wide.jpg", kind: "photo", size: "4.2 MB", date: "Today 8:41", hue: 42 },
  { id: "p4", name: "Pulpit_Close.jpg", kind: "photo", size: "3.8 MB", date: "Today 8:42", hue: 18 },
  { id: "p5", name: "Congregation_01.jpg", kind: "photo", size: "5.1 MB", date: "Today 8:44", hue: 210 },
  { id: "p6", name: "Baptism_Moment.jpg", kind: "photo", size: "4.6 MB", date: "Sat 16:02", hue: 168 },
  { id: "p7", name: "Praise_Clip.mov", kind: "video", size: "92 MB", date: "Sat 11:20", hue: 320 },
  { id: "p8", name: "Foyer_Banner.jpg", kind: "photo", size: "2.9 MB", date: "Fri 18:10", hue: 262 },
];

export const seedMedia: MediaItem[] = [
  { id: "m1", name: "Sanctuary Wide", kind: "background", folder: "Backgrounds", size: "6.4 MB", added: "2 days ago", favorite: true, hue: 222 },
  { id: "m2", name: "Cross Light", kind: "background", folder: "Backgrounds", size: "5.1 MB", added: "2 days ago", favorite: true, hue: 38 },
  { id: "m3", name: "Grace Chapel Logo", kind: "graphic", folder: "Church Graphics", size: "840 KB", added: "1 week ago", favorite: true, hue: 45 },
  { id: "m4", name: "Lower Third — Pastor", kind: "graphic", folder: "Church Graphics", size: "1.1 MB", added: "1 week ago", favorite: false, hue: 200 },
  { id: "m5", name: "Offering Loop", kind: "video", folder: "Videos", duration: "1:20", size: "48 MB", added: "3 days ago", favorite: false, hue: 150 },
  { id: "m6", name: "Welcome Bumper", kind: "video", folder: "Videos", duration: "0:18", size: "22 MB", added: "5 days ago", favorite: true, hue: 12 },
  { id: "m7", name: "Soft Piano Bed", kind: "audio", folder: "Audio", duration: "4:12", size: "8.4 MB", added: "1 week ago", favorite: false, hue: 280 },
  { id: "m8", name: "Choir Still", kind: "photo", folder: "Photos", size: "3.4 MB", added: "Yesterday", favorite: false, hue: 190 },
];

export const seedService: ServiceItem[] = [
  { id: "s1", kind: "welcome", title: "Welcome", detail: "Host greeting · foyer bumper", minutes: 3 },
  { id: "s2", kind: "prayer", title: "Opening Prayer", detail: "Pastor Ade", minutes: 2 },
  { id: "s3", kind: "worship", title: "Praise & Worship", detail: "Band set · 2 songs", minutes: 18 },
  { id: "s4", kind: "song", title: "Amazing Grace", detail: "Key of G · congregational", minutes: 5, payload: "amazing-grace" },
  { id: "s5", kind: "bible", title: "Bible Reading — John 3:16–17", detail: "KJV · on screen", minutes: 2, payload: "john-3-16" },
  { id: "s6", kind: "choir", title: "Choir Ministration", detail: "Special number", minutes: 6 },
  { id: "s7", kind: "announcement", title: "Announcements", detail: "Youth night · baptism class", minutes: 4 },
  { id: "s8", kind: "sermon", title: "Sermon", detail: "Born of the Spirit", minutes: 32 },
  { id: "s9", kind: "offering", title: "Offering", detail: "Offering loop + lower third", minutes: 5 },
  { id: "s10", kind: "prayer", title: "Closing Prayer", detail: "Benediction", minutes: 3 },
];

export const songs: Song[] = [
  {
    id: "amazing-grace",
    title: "Amazing Grace",
    author: "John Newton",
    key: "G",
    tempo: "72",
    publicDomain: true,
    sections: [
      { name: "Verse 1", lines: ["Amazing grace, how sweet the sound", "That saved a wretch like me", "I once was lost, but now am found", "Was blind, but now I see"] },
      { name: "Chorus", lines: ["Amazing grace, amazing grace", "How sweet the sound", "That saved a wretch like me"] },
      { name: "Verse 2", lines: ["'Twas grace that taught my heart to fear", "And grace my fears relieved", "How precious did that grace appear", "The hour I first believed"] },
      { name: "Chorus", lines: ["Amazing grace, amazing grace", "How sweet the sound", "That saved a wretch like me"] },
      { name: "Bridge", lines: ["When we've been there ten thousand years", "Bright shining as the sun", "We've no less days to sing God's praise", "Than when we first begun"] },
    ],
  },
  {
    id: "how-great",
    title: "How Great Thou Art",
    author: "Carl Boberg · trans. Stuart K. Hine",
    key: "Bb",
    tempo: "68",
    publicDomain: true,
    sections: [
      { name: "Verse 1", lines: ["O Lord my God, when I in awesome wonder", "Consider all the worlds Thy hands have made", "I see the stars, I hear the rolling thunder", "Thy power throughout the universe displayed"] },
      { name: "Chorus", lines: ["Then sings my soul, my Saviour God, to Thee", "How great Thou art, how great Thou art"] },
      { name: "Verse 2", lines: ["When through the woods and forest glades I wander", "And hear the birds sing sweetly in the trees", "When I look down from lofty mountain grandeur", "And hear the brook and feel the gentle breeze"] },
      { name: "Bridge", lines: ["And when I think that God, His Son not sparing", "Sent Him to die, I scarce can take it in"] },
    ],
  },
  {
    id: "way-maker",
    title: "Way Maker",
    author: "Sample structure for prototype",
    key: "E",
    tempo: "68",
    publicDomain: false,
    sections: [
      { name: "Verse 1", lines: ["[Licensed lyric placeholder]", "Verse line for live layout preview", "Replace with your CCLI text before go-live"] },
      { name: "Chorus", lines: ["[Chorus layout]", "Title line centered", "Response line underneath"] },
      { name: "Verse 2", lines: ["[Verse 2 layout]", "Second stanza preview", "Operator notes stay off the projector"] },
      { name: "Chorus", lines: ["[Chorus layout]", "Title line centered", "Response line underneath"] },
      { name: "Bridge", lines: ["[Bridge layout]", "Repeated declaration", "Build into final chorus"] },
    ],
  },
  {
    id: "goodness",
    title: "Goodness of God",
    author: "Sample structure for prototype",
    key: "A",
    tempo: "74",
    publicDomain: false,
    sections: [
      { name: "Verse 1", lines: ["[Licensed lyric placeholder]", "Opening testimony line", "Layout only — not song text"] },
      { name: "Chorus", lines: ["[Chorus layout]", "All my life You have been faithful", "Replace before presentation"] },
      { name: "Verse 2", lines: ["[Verse 2 layout]", "Continuing testimony", "Operator cue: keys swell"] },
      { name: "Bridge", lines: ["[Bridge layout]", "Your goodness is running after me", "Sample cue line for spacing"] },
    ],
  },
  {
    id: "beautiful-name",
    title: "What a Beautiful Name",
    author: "Sample structure for prototype",
    key: "D",
    tempo: "68",
    publicDomain: false,
    sections: [
      { name: "Verse 1", lines: ["[Licensed lyric placeholder]", "Opening name declaration", "Preview spacing only"] },
      { name: "Chorus", lines: ["[Chorus layout]", "What a beautiful name it is", "Sample cue — use licensed copy"] },
      { name: "Verse 2", lines: ["[Verse 2 layout]", "You didn't want heaven without us", "Placeholder for arrangement"] },
      { name: "Bridge", lines: ["[Bridge layout]", "Death could not hold You", "Final lift into chorus"] },
    ],
  },
];

export const kjv: Record<string, string[]> = {
  "John 3": [
    "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:",
    "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him.",
    "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God.",
    "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?",
    "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit.",
    "Marvel not that I said unto thee, Ye must be born again.",
    "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.",
    "Nicodemus answered and said unto him, How can these things be?",
    "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?",
    "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
    "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
    "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
    "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:",
    "That whosoever believeth in him should not perish, but have eternal life.",
    "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    "For God sent not his Son into the world to condemn the world; but that the world through him might be saved.",
    "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God.",
  ],
  "Psalm 23": [
    "The LORD is my shepherd; I shall not want.",
    "He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
    "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
    "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
    "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.",
  ],
  "John 1": [
    "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "The same was in the beginning with God.",
    "All things were made by him; and without him was not any thing made that was made.",
    "In him was life; and the life was the light of men.",
    "And the light shineth in darkness; and the darkness comprehended it not.",
  ],
  "Romans 8": [
    "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.",
    "For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.",
    "For what the law could not do, in that it was weak through the flesh, God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh:",
  ],
};

export const books = ["John", "Psalm", "Romans", "Genesis", "Matthew", "Isaiah"];

export const themes: ThemePreset[] = [
  {
    id: "grace",
    name: "Grace Chapel Gold",
    church: "Grace Chapel",
    primary: "#c9a44a",
    accent: "#f4efe4",
    font: "Fraunces",
    lyricStyle: "Centered serif, soft gold rule",
    verseStyle: "Large serif verse, reference underneath",
    announceStyle: "Warm card, gold eyebrow",
    lowerThird: "Left bar · name + role",
    bg: "cross",
  },
  {
    id: "midnight",
    name: "Midnight Sanctuary",
    church: "Grace Chapel",
    primary: "#7eb6ff",
    accent: "#eef4ff",
    font: "Outfit",
    lyricStyle: "Clean sans, wide tracking",
    verseStyle: "Sans verse, blue reference",
    announceStyle: "Glass panel, cool edge",
    lowerThird: "Pill lower third",
    bg: "sanctuary",
  },
  {
    id: "harvest",
    name: "Harvest Sunday",
    church: "Grace Chapel",
    primary: "#e07a3d",
    accent: "#fff6ee",
    font: "Fraunces",
    lyricStyle: "Warm serif, ember underline",
    verseStyle: "Scripture block on amber wash",
    announceStyle: "Bold harvest banner",
    lowerThird: "Amber name plate",
    bg: "harvest",
  },
  {
    id: "easter",
    name: "Easter Dawn",
    church: "Grace Chapel",
    primary: "#f2d7a2",
    accent: "#fffaf2",
    font: "Fraunces",
    lyricStyle: "Light serif on dawn gradient",
    verseStyle: "High contrast dawn verse",
    announceStyle: "Soft dawn card",
    lowerThird: "Dawn lower third",
    bg: "dawn",
  },
];
